# MCP Server Gateway Interface Default Configuration
# This file defines the default configuration for the MCP Server Gateway interface

# Import gateway configuration
- import: &gateway_config !include gateway.yaml:gateway_config

# MCP server configuration
- mcp_server_config: &mcp_server_config
    mcp_server_scopes: ${MCP_SERVER_SCOPES, "*:*:*"}
    mcp_server_port: ${MCP_SERVER_PORT, 8080}
    mcp_server_host: ${MCP_SERVER_HOST, 0.0.0.0}
    mcp_server_transport: ${MCP_SERVER_TRANSPORT, sse}

# Response format prompt
- response_format_prompt: &response_format_prompt >
    Please provide clear, concise responses.
