version: 3

project:
  id: SolaceLabs_sam-webhook-gateway
  name: sam-webhook-gateway
  labels:
    - solaceai
    - solace-agent-mesh-core-plugins

vendoredDependencies:
  forceRescans: false
  scanMethod: CLILicenseScan

telemetry:
  scope: full
