version: 3

project:
  id: SolaceLabs_sam-nuclia-tool
  name: sam-nuclia-tool
  labels:
    - solaceai
    - solace-agent-mesh-core-plugins

vendoredDependencies:
  forceRescans: false
  scanMethod: CLILicenseScan

telemetry:
  scope: full
