# This is the configuration file for the jde orders agent
#

---
log:
  stdout_log_level: INFO
  log_file_level: INFO
  log_file: solace_ai_connector.log

shared_config:
  - broker_config: &broker_connection
      dev_mode: ${SOLACE_DEV_MODE, false}
      broker_url: ${SOLACE_BROKER_URL}
      broker_username: ${SOLACE_BROKER_USERNAME}
      broker_password: ${SOLACE_BROKER_PASSWORD}
      broker_vpn: ${SOLACE_BROKER_VPN}

flows:

  # Flow to handle action requests
  - name: mongodb_action_request_processor
    components:
      # Input from a Solace broker
      - component_name: broker_input
        component_module: broker_input
        component_config:
          <<: *broker_connection
          payload_encoding: utf-8
          payload_format: json
          broker_queue_name: ${SOLACE_AGENT_MESH_NAMESPACE}agent_mongodb_action_request
          broker_subscriptions:
            - topic: ${SOLACE_AGENT_MESH_NAMESPACE}solace-agent-mesh/v1/actionRequest/*/*/mongodb/>
              qos: 1

      # Custom component to process the action request
      - component_name: action_request_processor
         # path is completed at build time
        component_module: {{MODULE_DIRECTORY}}.agents.mongodb.mongodb_agent_component
        component_config:
          llm_service_topic: ${SOLACE_AGENT_MESH_NAMESPACE}solace-agent-mesh/v1/llm-service/request/general-good/
          embedding_service_topic: ${SOLACE_AGENT_MESH_NAMESPACE}solace-agent-mesh/v1/embedding-service/request/text/
          agent_name: mongodb_agent
          database_host: ${MONGO_HOST}
          database_port: ${MONGO_PORT}
          database_user: ${MONGO_USER}
          database_password: ${MONGO_PASSWORD}
          database_name: ${MONGO_DB}
          database_collection: ${MONGO_COLLECTION}
          database_purpose: >
            This database purpose. what's stored in it, how it's used, etc.
          data_description: >
            Details of all the document structure, their meaning, how they relate and how to use them.
            Potentially some example use cases too.
          auto_detect_schema: true
          # Pass required configuration to the component
        broker_request_response:
          enabled: true
          broker_config: *broker_connection
          request_expiry_ms: 120000
          payload_encoding: utf-8
          payload_format: json
          response_topic_prefix: ${SOLACE_AGENT_MESH_NAMESPACE}solace-agent-mesh/v1
          response_queue_prefix: ${SOLACE_AGENT_MESH_NAMESPACE}solace-agent-mesh/v1
        component_input:
          source_expression: input.payload

      # Output to a Solace broker
      - component_name: broker_output
        component_module: broker_output
        component_config:
          <<: *broker_connection
          payload_encoding: utf-8
          payload_format: json
          copy_user_properties: true
