# NOTE that these are just examples that should be changed
- event_mesh_input_config: &event_mesh_input_config
    identity: user_event_mesh
    event_handlers:
      - name: jira_event_handler
        output_handler_name: jira_output_handler
        subscriptions:
          - topic: jira/issue/create/>
            qos: 1
        input_expression: >
          template:Raise a standalone Jira Task in the EPT project that tracks the work to triage this newly created issue below. It must be in the EPT project and it should not link to any issues. Here is the new issue:{{text://input.payload}}
        payload_encoding: utf-8
        payload_format: json

- event_mesh_output_config: &event_mesh_output_config
    output_handlers:
      - name: jira_output_handler
        topic: jira/issue/create/processed
        payload_encoding: utf-8
        payload_format: json

- response_format_prompt_config: &response_format_prompt >
      The response must be well formed JSON in the format:
            <response-json>
            ... JSON response ...
            </response-json>




