# This is the configuration file for the rag agent
#
# It fulfills a few functions:
# 1. A flow to do periodic registration of this agent with the orchestrator
# 2. A flow to process action requests and produce action responses

---
log:
  stdout_log_level: INFO
  log_file_level: INFO
  log_file: solace_ai_connector.log

shared_config:
  - broker_config: &broker_connection
      dev_mode: ${SOLACE_DEV_MODE}
      broker_url: ${SOLACE_BROKER_URL}
      broker_username: ${SOLACE_BROKER_USERNAME}
      broker_password: ${SOLACE_BROKER_PASSWORD}
      broker_vpn: ${SOLACE_BROKER_VPN}
      temporary_queue: ${USE_TEMPORARY_QUEUES}

flows:
  # Flow to handle action requests
  - name: rag_action_request_processor
    components:
      # Input from a Solace broker
      - component_name: broker_input
        component_module: broker_input
        component_config:
          <<: *broker_connection
          payload_encoding: utf-8
          payload_format: json
          broker_queue_name: ${SOLACE_AGENT_MESH_NAMESPACE}agent_rag_action_request
          broker_subscriptions:
            # Subscribe to all rag actions - note that if we
            # wanted to handle some rag actions elsewhere, we would
            # need to be more specific here
            - topic: ${SOLACE_AGENT_MESH_NAMESPACE}solace-agent-mesh/v1/actionRequest/*/*/rag/>
              qos: 1

      # Custom component to process the action request
      - component_name: action_request_processor
        component_base_path: .
        # path is completed at build time
        component_module: {{MODULE_DIRECTORY}}.agents.rag.rag_agent_component
        component_config:
          llm_service_topic: ${SOLACE_AGENT_MESH_NAMESPACE}solace-agent-mesh/v1/llm-service/request/general-good/
          embedding_service_topic: ${SOLACE_AGENT_MESH_NAMESPACE}solace-agent-mesh/v1/embedding-service/request/text/
          agent_name: rag
          # Scanner configuration
          scanner:
            batch: true
            use_memory_storage: true
            source:
              type: filesystem
              directories:
                - "DIRECTORY PATH" # e.g. "/path/to/documents"
              filters:
                file_formats:
                  - ".txt"
                  - ".pdf"
                  - ".docx"
                  - ".doc"
                  - ".md"
                  - ".html"
                  - ".csv"
                  - ".json"
                  - ".odt"
                  - ".xlsx"
                  - ".xls"
                max_file_size: 10240  # in KB (10MB)
            database:
              type: postgresql
              dbname: rag_metadata
              host: localhost
              port: 5432
              user: admin
              password: admin
            schedule:
              interval: 60 # seconds
          
          # Preprocessor configuration
          preprocessor:
            default_preprocessor:
              type: enhanced
              params:
                  lowercase: true
                  normalize_whitespace: true
                  remove_stopwords: false
                  remove_punctuation: false
                  remove_numbers: false
                  remove_non_ascii: false
                  remove_urls: true
                  remove_emails: false
                  remove_html_tags: false
            
            preprocessors:
              # Text file configurations
              text:
                type: text
                params:
                  lowercase: true
                  normalize_whitespace: true
                  remove_stopwords: false
                  remove_punctuation: true
                  remove_numbers: false
                  remove_non_ascii: false
                  remove_urls: true
                  remove_emails: false
                  remove_html_tags: false
              
              # Document file configurations
              pdf:
                type: document
                params:
                  lowercase: true
                  normalize_whitespace: true
                  remove_stopwords: false
                  remove_punctuation: true
                  remove_numbers: false
                  remove_non_ascii: true
                  remove_urls: true
                  remove_emails: true
                  remove_html_tags: false
              
              doc:
                type: document
                params:
                  lowercase: true
                  normalize_whitespace: true
                  remove_stopwords: false
                  remove_punctuation: true
                  remove_numbers: false
                  remove_non_ascii: true
                  remove_urls: true
                  remove_emails: true
                  remove_html_tags: false

              odt:
                type: document
                params:
                  lowercase: true
                  normalize_whitespace: true
                  remove_stopwords: false
                  remove_punctuation: true
                  remove_numbers: false
                  remove_non_ascii: true
                  remove_urls: true
                  remove_emails: true
                  remove_html_tags: false
              
              # Structured data configurations
              json:
                type: structured
                params:
                  lowercase: true
                  normalize_whitespace: true
                  remove_stopwords: false
                  remove_punctuation: false
                  remove_numbers: false
                  remove_non_ascii: false
                  remove_urls: true
                  remove_emails: true
                  remove_html_tags: false
              
              html:
                type: html
                params:
                  lowercase: true
                  normalize_whitespace: true
                  remove_stopwords: false
                  remove_punctuation: false
                  remove_numbers: false
                  remove_non_ascii: false
                  remove_urls: true
                  remove_emails: true
                  remove_html_tags: false
              
              markdown:
                type: markdown
                params:
                  lowercase: true
                  normalize_whitespace: true
                  remove_stopwords: false
                  remove_punctuation: false
                  remove_numbers: false
                  remove_non_ascii: false
                  remove_urls: true
                  remove_emails: true
                  remove_html_tags: false

              csv:
                type: csv
                params:
                  lowercase: true
                  normalize_whitespace: true
                  remove_stopwords: false
                  remove_punctuation: true
                  remove_numbers: false
                  remove_non_ascii: false
                  remove_urls: true
                  remove_emails: true
                  remove_html_tags: false

              xls:
                type: xls
                params:
                  lowercase: true
                  normalize_whitespace: true
                  remove_stopwords: false
                  remove_punctuation: true
                  remove_numbers: false
                  remove_non_ascii: false
                  remove_urls: true
                  remove_emails: true
                  remove_html_tags: false
          
          # Text splitter configuration
          splitter:
            default_splitter:
              type: character
              params:
                chunk_size: 4096 # minimum chunk size
                chunk_overlap: 800
                separator: " "
            splitters:
              # Text file configurations
              text:
                type: character
                params:
                  chunk_size: 4096 # minimum chunk size
                  chunk_overlap: 800
                  separator: " "
                  is_separator_regex: false
                  keep_separator: true
                  strip_whitespace: true
              txt:
                type: token
                params:
                  chunk_size: 1024
                  chunk_overlap: 200
                  encoding_name: "cl100k_base"
              # Structured data configurations
              json:
                type: recursive_json
                params:
                  chunk_size: 100
                  chunk_overlap: 10
              html:
                type: html
                params:
                  chunk_size: 4096
                  chunk_overlap: 800
                  tags_to_extract: ["p", "h1", "h2", "h3", "li"]
              markdown:
                type: markdown
                params:
                  chunk_size: 4096
                  chunk_overlap: 800
                  headers_to_split_on: ["#", "##", "###", "####", "#####", "######"]
                  strip_headers: false
              csv:
                type: csv
                params:
                  chunk_size: 4096 # chunk size in number of rows
                  include_header: false
              # Add Xml, Odt, Xlsx, and other formats as needed
          # Embedding configuration
          embedding:
            embedder_type: "openai"
            embedder_params:
              # OpenAI embeddings
              model: ${OPENAI_EMBEDDING_MODEL}
              api_key: ${OPENAI_API_KEY}
              base_url: ${OPENAI_API_ENDPOINT}
              batch_size: 1
            normalize_embeddings: True

            # # Hugging Face embeddings
            # embedder_type: "huggingface"
            # embedder_params:
            #     model: ${HF_EMBEDDING_MODEL, "sentence-transformers/all-MiniLM-L6-v2"}
            #     dimensions: 1536
            #     device: ${HF_DEVICE}
            #     batch_size: 32

            #   # Cohere embeddings
            #   embedder_type: "cohere"
            #   embedder_params:
            #     model: ${COHERE_EMBEDDING_MODEL, "embed-english-v3.0"}
            #     dimensions: 1024
            #     api_key: ${COHERE_API_KEY}
            #     batch_size: 96

            #   # Local embeddings
            #   embedder_type: "local"
            #   embedder_params:
            #     model: ${LOCAL_EMBEDDING_MODEL, "sentence-transformers/all-MiniLM-L6-v2"}
            #     dimensions: 1536
            #     device: ${LOCAL_DEVICE}
            #     batch_size: 32
          
          # Vector database configuration
          vector_db:
            # Qdrant
            db_type: "qdrant"
            db_params:
              url: ${QDRANT_URL}
              api_key: ${QDRANT_API_KEY}
              collection_name: ${QDRANT_COLLECTION}
              embedding_dimension: ${QDRANT_EMBEDDING_DIMENSION}

            # Chroma DB configuration
            # db_type: "chroma"
            # db_params:
            #   host: ${CHROMA_HOST}
            #   port: ${CHROMA_PORT}
            #   collection_name: ${CHROMA_COLLECTION}
            #   persist_directory: ${CHROMA_PERSIST_DIR, "./chroma_db"}
            #   embedding_function: ${CHROMA_EMBEDDING_FUNCTION}
            #   embedding_dimension: ${QDRANT_EMBEDDING_DIMENSION}  # Added embedding dimension
            
            # Pinecone configuration
            # db_type: "pinecone"
            # db_params:
            #   api_key: ${PINECONE_API_KEY}
            #   index_name: ${PINECONE_INDEX}
            #   namespace: ${PINECONE_NAMESPACE}
            #   embedding_dimension: ${PINECONE_DIMENSIONS}
            #   metric: ${PINECONE_METRIC}
            #   cloud: ${PINECONE_CLOUD}
            #   region: ${PINECONE_REGION}


            # # PostgreSQL with pgvector
            # db_type: "pgvector"
            # db_params:
            #   host: ${PGVECTOR_HOST, "localhost"}
            #   port: ${PGVECTOR_PORT, 5432}
            #   database: ${PGVECTOR_DATABASE, "vectordb"}
            #   user: ${PGVECTOR_USER, "postgres"}
            #   password: ${PGVECTOR_PASSWORD}
            #   table_name: ${PGVECTOR_TABLE, "document_embeddings"}
            #   embedding_dimension: ${PGVECTOR_DIMENSION, 1024}

          llm:
            load_balancer:
              - model_name: "gpt-4o" # model alias
                litellm_params:
                      model: openai/${OPENAI_MODEL_NAME}
                      api_key: ${OPENAI_API_KEY}
                      api_base: ${OPENAI_API_ENDPOINT}
                      temperature: 0.01
                      # add any other parameters here
              # - model_name: "claude-3-5-sonnet" # model alias
              #   litellm_params:
              #         model: ${ANTHROPIC_MODEL_NAME}
              #         api_key: ${ANTHROPIC_API_KEY}
              #         api_base: ${ANTHROPIC_API_ENDPOINT}
              #         # add any other parameters here
              # add more models here

          retrieval:
            top_k: 7

        broker_request_response:
          enabled: true
          broker_config: *broker_connection
          request_expiry_ms: 120000
          payload_encoding: utf-8
          payload_format: json
          response_topic_prefix: ${SOLACE_AGENT_MESH_NAMESPACE}solace-agent-mesh/v1
          response_queue_prefix: ${SOLACE_AGENT_MESH_NAMESPACE}solace-agent-mesh/v1
        component_input:
          source_expression: input.payload

      # Output to a Solace broker
      - component_name: broker_output
        component_module: broker_output
        component_config:
          <<: *broker_connection
          payload_encoding: utf-8
          payload_format: json
          copy_user_properties: true
