# Configuration used for fossa scan
version: 3

project:
  locator: SolaceLabs_sam-mongodb
  id: SolaceLabs_sam-mongodb
  name: sam-mongodb
  labels:
    - solaceai
    - solace-agent-mesh-core-plugins

vendoredDependencies:
  forceRescans: false
  scanMethod: CLILicenseScan

telemetry:
  scope: full
