# This is a configuration template for the SAM RAG Agent Plugin.
#
# Plugin Metadata:
# Name: sam-rag-agent
# Version: 0.1.0
# Description: This plugin allows you to import one RAG agent as action to be used in your SAM project.
# Author: SolaceLabs <solacelabs@solace.com>

log:
  stdout_log_level: INFO
  log_file_level: DEBUG
  log_file: __COMPONENT_KEBAB_CASE_NAME__.log

# To use the `shared_config.yaml` file, uncomment the following line and remove the `shared_config` section below.
# !include ../shared_config.yaml
shared_config:
  - broker_connection: &broker_connection
      dev_mode: ${SOLACE_DEV_MODE, false}
      broker_url: ${SOLACE_BROKER_URL, ws://localhost:8080}
      broker_username: ${SOLACE_BROKER_USERNAME, default}
      broker_password: ${SOLACE_BROKER_PASSWORD, default}
      broker_vpn: ${SOLACE_BROKER_VPN, default}
      temporary_queue: ${USE_TEMPORARY_QUEUES, true}

  - models:
    general: &general_model
      model: ${LLM_SERVICE_GENERAL_MODEL_NAME} # Use env var for model name
      api_base: ${LLM_SERVICE_ENDPOINT} # Use env var for endpoint URL
      api_key: ${LLM_SERVICE_API_KEY} # Use env var for API key

  - services:
    # Default session service configuration
    session_service: &default_session_service
      type: "memory"
      default_behavior: "PERSISTENT"
    
    # Default artifact service configuration
    artifact_service: &default_artifact_service
      type: "filesystem"
      base_path: "/tmp/a2a_rag_agent_artifacts"
      artifact_scope: "app"

apps:
  - name: __COMPONENT_KEBAB_CASE_NAME__-app
    app_module: solace_agent_mesh.agent.sac.app 
    broker:
      <<: *broker_connection
    app_config:
      namespace: "${NAMESPACE}" # Your A2A topic namespace
      agent_name: "__COMPONENT_PASCAL_CASE_NAME__" 
      display_name: "__COMPONENT_SPACED_CAPITALIZED_NAME__ Agent" 
      supports_streaming: true # RAG agent supports streaming responses

      model: *general_model 
      instruction: |
        You are a RAG (Retrieval Augmented Generation) agent that can ingest documents and retrieve relevant information.
        You can search for information in the ingested documents and provide augmented responses.
        Use the 'ingest_document' tool to add new documents to the system.
        Use the 'search_documents' tool to find relevant information based on user queries.

      # --- Configurable Agent Initialization & Cleanup ---
      agent_init_function:
        module: "sam_rag.lifecycle"
        name: "initialize_rag_agent"
        config:
          scanner:
            batch: true
            use_memory_storage: true
            sources:
              - type: filesystem
                directories:
                  - "${DOCUMENTS_PATH}" # Path to documents directory
                filters:
                  file_formats:
                    - ".txt"
                    - ".pdf"
                    - ".docx"
                    - ".md"
                    - ".html"
                    - ".csv"
                    - ".json"
                  max_file_size: 10240  # in KB (10MB)
                schedule:
                  interval: 60 # seconds
              
                            # Google Drive source with Service Account Authentication
              - type: google_drive
                provider: google_drive
                auth_type: "service_account"  # Use Service Account instead of OAuth2
                service_account_key_path: "${GOOGLE_SERVICE_ACCOUNT_KEY_PATH}" # e.g. "/path/to/service-account-key.json"
                folders:
                  - folder_id: "${GOOGLE_DRIVE_FOLDER_ID_1}" # e.g. "1BxiMVs0XRA5nFMdKvBdBZjgmUUqptlbs74OgvE2upms"
                    name: "Documents"
                    recursive: true
                    type: "personal"
                  - folder_id: "${GOOGLE_DRIVE_FOLDER_ID_2}" # e.g. "0AEd3EhGff_FmUk9PVA"
                    name: "Shared Drive"
                    recursive: true
                    type: "shared_drive"
                filters:
                  file_formats:
                    - ".txt"
                    - ".pdf"
                    - ".docx"
                    - ".doc"
                    - ".md"
                    - ".html"
                    - ".csv"
                    - ".json"
                    - ".odt"
                    - ".xlsx"
                    - ".xls"
                  max_file_size: 10240  # in KB (10MB)
                  include_google_formats: true  # Include Google Docs, Sheets, Slides
                real_time:
                  enabled: true
                  webhook_url: "${GOOGLE_DRIVE_WEBHOOK_URL}" # e.g. "https://your-domain.com/webhook/google-drive"
                  polling_interval: 300  # Fallback polling in seconds (5 minutes)
                          # OneDrive source
              - type: onedrive
                provider: onedrive
                client_id: "${ONEDRIVE_CLIENT_ID}"
                client_secret: "${ONEDRIVE_CLIENT_SECRET}"
                tenant_id: "${ONEDRIVE_TENANT_ID}"
                account_type: "business"  # or "personal"
                folders:
                  - path: "/Documents"
                    name: "Documents"
                    recursive: true
                  - path: "/Shared Documents"
                    name: "Shared Documents"
                    recursive: true
                filters:
                  file_formats:
                    - ".txt"
                    - ".pdf"
                    - ".docx"
                    - ".doc"
                    - ".md"
                    - ".html"
                    - ".csv"
                    - ".json"
                    - ".odt"
                    - ".xlsx"
                    - ".xls"
                  max_file_size: 10240  # in KB (10MB)
                real_time:
                  enabled: true
                  webhook_url: "${ONEDRIVE_WEBHOOK_URL}"
                  polling_interval: 300  # 5 minutes
              
              # AWS S3 source
              - type: s3
                provider: s3
                bucket_name: "${S3_BUCKET_NAME}"
                region: "${S3_REGION}"
                access_key_id: "${AWS_ACCESS_KEY_ID}"
                secret_access_key: "${AWS_SECRET_ACCESS_KEY}"
                folders:
                  - prefix: "documents/"
                    name: "Documents"
                    recursive: true
                  - prefix: "reports/"
                    name: "Reports"
                    recursive: true
                filters:
                  file_formats:
                    - ".txt"
                    - ".pdf"
                    - ".docx"
                    - ".doc"
                    - ".md"
                    - ".html"
                    - ".csv"
                    - ".json"
                    - ".odt"
                    - ".xlsx"
                    - ".xls"
                  max_file_size: 10240  # in KB (10MB)
                real_time:
                  enabled: true
                  sqs_queue_url: "${S3_SQS_QUEUE_URL}"
                  polling_interval: 300  # 5 minutes
          
          # Preprocessor configuration
          preprocessor:
            default_preprocessor:
              type: enhanced
              params:
                  lowercase: true
                  normalize_whitespace: true
                  remove_stopwords: false
                  remove_punctuation: false
                  remove_numbers: false
                  remove_non_ascii: false
                  remove_urls: true
                  remove_emails: false
                  remove_html_tags: false
            
            # Text file configurations
            text:
              type: text
              params:
                lowercase: true
                normalize_whitespace: true
                remove_stopwords: false
                remove_punctuation: true
                remove_numbers: false
                remove_non_ascii: false
                remove_urls: true
                remove_emails: false
                remove_html_tags: false
              
            # Document file configurations
            pdf:
              type: document
              params:
                lowercase: true
                normalize_whitespace: true
                remove_stopwords: false
                remove_punctuation: true
                remove_numbers: false
                remove_non_ascii: true
                remove_urls: true
                remove_emails: true
                remove_html_tags: false
              
            doc:
              type: document
              params:
                lowercase: true
                normalize_whitespace: true
                remove_stopwords: false
                remove_punctuation: true
                remove_numbers: false
                remove_non_ascii: true
                remove_urls: true
                remove_emails: true
                remove_html_tags: false

            odt:
              type: document
              params:
                lowercase: true
                normalize_whitespace: true
                remove_stopwords: false
                remove_punctuation: true
                remove_numbers: false
                remove_non_ascii: true
                remove_urls: true
                remove_emails: true
                remove_html_tags: false
              
            # Structured data configurations
            json:
              type: structured
              params:
                lowercase: true
                normalize_whitespace: true
                remove_stopwords: false
                remove_punctuation: false
                remove_numbers: false
                remove_non_ascii: false
                remove_urls: true
                remove_emails: true
                remove_html_tags: false
              
            html:
              type: html
              params:
                lowercase: true
                normalize_whitespace: true
                remove_stopwords: false
                remove_punctuation: false
                remove_numbers: false
                remove_non_ascii: false
                remove_urls: true
                remove_emails: true
                remove_html_tags: false
              
            markdown:
              type: markdown
              params:
                lowercase: true
                normalize_whitespace: true
                remove_stopwords: false
                remove_punctuation: false
                remove_numbers: false
                remove_non_ascii: false
                remove_urls: true
                remove_emails: true
                remove_html_tags: false

            csv:
              type: csv
              params:
                lowercase: true
                normalize_whitespace: true
                remove_stopwords: false
                remove_punctuation: true
                remove_numbers: false
                remove_non_ascii: false
                remove_urls: true
                remove_emails: true
                remove_html_tags: false

            xls:
               type: xls
               params:
                lowercase: true
                normalize_whitespace: true
                remove_stopwords: false
                remove_punctuation: true
                remove_numbers: false
                remove_non_ascii: false
                remove_urls: true
                remove_emails: true
                remove_html_tags: false
        
          # Text splitter configuration
          splitter:
            default_splitter:
              type: character
              params:
                chunk_size: 2048 # minimum chunk size
                chunk_overlap: 800
                separator: " "
            splitters:
              # Text file configurations
              text:
                type: character
                params:
                  chunk_size: 2048 # minimum chunk size
                  chunk_overlap: 800
                  separator: " "
                  is_separator_regex: false
                  keep_separator: true
                  strip_whitespace: true
              txt:
                type: character
                params:
                  chunk_size: 2048 # minimum chunk size
                  chunk_overlap: 800
                  separator: "\n"
                  is_separator_regex: false
                  keep_separator: true
                  strip_whitespace: true
              # Structured data configurations
              json:
                type: recursive_json
                params:
                  chunk_size: 200
                  chunk_overlap: 50
              html:
                type: html
                params:
                  chunk_size: 2048
                  chunk_overlap: 800
                  tags_to_extract: ["p", "h1", "h2", "h3", "li"]
              markdown:
                type: markdown
                params:
                  chunk_size: 2048
                  chunk_overlap: 800
                  headers_to_split_on: ["#", "##", "###", "####", "#####", "######"]
                  strip_headers: false
              csv:
                type: csv
                params:
                  chunk_size: 2048 # chunk size in number of rows
                  include_header: false
                # Add Xml, Odt, Xlsx, and other formats as needed
            # Embedding configuration
          
          embedding:
            embedder_type: "openai"
            embedder_params:
              model: "${OPENAI_EMBEDDING_MODEL}"
              api_key: "${OPENAI_API_KEY}"
              api_base: "${OPENAI_API_ENDPOINT}"
              batch_size: 32
            normalize_embeddings: true
          
          vector_db:
            db_type: "qdrant"
            db_params:
              url: "${QDRANT_URL}"
              api_key: "${QDRANT_API_KEY}"
              collection_name: "${QDRANT_COLLECTION}"
              embedding_dimension: ${QDRANT_EMBEDDING_DIMENSION}
          
          llm:
            load_balancer:
              - model_name: "gpt-4o"
                litellm_params:
                  model: openai/${OPENAI_MODEL_NAME}
                  api_key: ${OPENAI_API_KEY}
                  api_base: ${OPENAI_API_ENDPOINT}
                  temperature: 0.01
          
          retrieval:
            top_k: 5

      agent_cleanup_function:
        module: "sam_rag.lifecycle"
        name: "cleanup_rag_agent_resources"

      # --- ADK Tools Configuration ---
      tools:
        - tool_type: python
          component_module: "sam_rag.tools"
          function_name: "ingest_document"
          required_scopes: ["rag:ingest:write"]
        
        - tool_type: python
          component_module: "sam_rag.tools"
          function_name: "search_documents"
          required_scopes: ["rag:search:read"]

      session_service: *default_session_service
      artifact_service: *default_artifact_service

      # Enable built-in artifact tools for the LLM to use
      enable_builtin_artifact_tools:
        enabled: true

      # Agent Card, Discovery, and Inter-Agent Communication
      agent_card:
        description: "RAG Agent that can ingest documents and retrieve relevant information based on queries."
        defaultInputModes: ["text", "file"]
        defaultOutputModes: ["text", "file"]
        skills:
          - id: "document_ingestion"
            name: "Document Ingestion"
            description: "Ingest documents from various sources into the RAG system."
            examples:
              - "Please ingest this document about climate change."
              - "Add this PDF to the knowledge base."
          - id: "document_retrieval"
            name: "Document Retrieval"
            description: "Search for relevant information in ingested documents."
            examples:
              - "What information do we have about renewable energy?"
              - "Find documents related to machine learning algorithms."

      agent_card_publishing:
        interval_seconds: 30

      agent_discovery:
        enabled: true

      inter_agent_communication:
        allow_list: ["*"]
        deny_list: []
        request_timeout_seconds: 60
